export { Header } from "./header/Header";
export { Detail } from "./detail/Detail";
export { Beta } from "./beta/Beta";
export { Button } from "./button/Button";
export { Info } from "./info/Info";
export { Picture } from "./picture/Picture";
export { Price } from "./price/Price";
export { Tool } from "./tool/Tool";
export { Footer } from "./footer/Footer";
