import Head from "next/head";
import styles from "../styles/Features.module.scss";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Tool from "../components/Tool";
import Beta from "../components/Beta";

import { tool } from "../data/toolsFeatures";
export default function Home() {
    const desktop = 1180;
    const tablet = 720;

    return (
        <div className={styles.main_container}>
            <Head>
                <title>
                    Frontend Mentor | Photosnap Website Challenge |Features
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="/assets/features/desktop/hero.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="/assets/features/tablet/hero.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img src="/assets/features/mobile/hero.jpg" alt="" />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info_wrap}>
                        <h1> FEATURES</h1>
                        <p>
                            We make sure all of our features are designed to be
                            loved by every aspiring and even professional
                            photograpers who wanted to share their stories.
                        </p>
                    </div>
                </div>
            </main>
            <section
                className={styles.section_tools}
                aria-label="features tools"
            >
                <div className={styles.tools_container}>
                    {tool.map((item, index) => (
                        <Tool
                            key={index}
                            icon={item.icon}
                            header={item.header}
                            paragraph={item.paragraph}
                        />
                    ))}
                </div>
            </section>
            <Beta />
            <Footer />
        </div>
    );
}
