import Head from "next/head";
import styles from "../styles/Features.module.scss";
import Responsive from "../svg/responsive.svg";
import Unlimit from "../svg/no-limit.svg";
import Embed from "../svg/embed.svg";
import Custom from "../svg/custom-domain.svg";
import Boost from "../svg/boost-exposure.svg";
import Drag from "../svg/drag-drop.svg";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Tool from "../components/Tool";
import Beta from "../components/Beta";
export default function Home() {
    const desktop = 1180;
    const tablet = 720;
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Photosnap Website Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>
            <Header />

            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="/assets/features/desktop/hero.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="/assets/features/tablet/hero.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img src="/assets/features/mobile/hero.jpg" alt="" />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info_wrap}>
                        <h1> FEATURES</h1>
                        <p>
                            We make sure all of our features are designed to be
                            loved by every aspiring and even professional
                            photograpers who wanted to share their stories.
                        </p>
                    </div>
                </div>
            </main>
            <section
                className={styles.section_tools}
                aria-label="features tools"
            >
                <div className={styles.tools_container}>
                    <Tool
                        icon={<Responsive />}
                        header="100% Responsive"
                        paragraph="No matter which the device you’re on, our site is fully
                        responsive and stories look beautiful on any screen."
                    />
                    <Tool
                        icon={<Unlimit />}
                        header=" No Photo Upload Limit"
                        paragraph="Our tool has no limits on uploads or bandwidth. Freely upload in bulk and 
                    share all of your stories in one go."
                    />
                    <Tool
                        icon={<Embed />}
                        header="Available to Embed"
                        paragraph=" Embed Tweets, Facebook posts, Instagram media, Vimeo or YouTube videos, 
                Google Maps, and more."
                    />

                    <Tool
                        icon={<Custom />}
                        header="Custom Domain"
                        paragraph="With Photosnap subscriptions you can host your stories on your own domain. You can 
                        also remove our branding!"
                    />
                    <Tool
                        icon={<Boost />}
                        header=" Boost Your Exposure"
                        paragraph="Users that viewed your story or gallery can easily get notifed of new and featured 
                        stories with our built in mailing list."
                    />

                    <Tool
                        icon={<Drag />}
                        header="Drag & Drop Image"
                        paragraph=" Easily drag and drop your image and get beautiful shots everytime. No over the top 
                        tooling to add friction to creating stories."
                    />
                </div>
            </section>
            <Beta />
            <Footer />
        </div>
    );
}
