import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Responsive from "../svg/responsive.svg";
import Unlimit from "../svg/no-limit.svg";
import Embed from "../svg/embed.svg";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Button from "../components/Button";
import Detail from "../components/Detail";
import Picture from "../components/Picture";
import Tool from "../components/Tool";
export default function Home() {
    const desktop = 1180;
    const tablet = 720;
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Photosnap Website Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>
            <Header />

            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="/assets/home/desktop/create-and-share.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="/assets/home/tablet/create-and-share.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img
                        src="/assets/home/mobile/create-and-share.jpg"
                        alt=""
                    />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info_wrap}>
                        <h1> CREATE AND SHARE YOUR PHOTO STORIES</h1>
                        <p>
                            Photosnap is a platform for photographers and visual
                            storytellers. We make it easy to share photos, tell
                            stories and connect with others.
                        </p>
                        <Button
                            title="GET AN INVITE"
                            color="white"
                            space="main"
                            arrow="white_arrow"
                        />
                    </div>
                </div>
            </main>
            <section className={styles.section_details} aria-label="details">
                <Detail
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/home/desktop/beautiful-stories.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <source
                                srcSet="/assets/home/tablet/beautiful-stories.jpg"
                                media={`(min-width:${tablet}px)`}
                            />
                            <img
                                src="/assets/home/mobile/beautiful-stories.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="
                    BEAUTIFUL STORIES EVERY TIME"
                    paragraph="
                            We provide design templates to ensure your stories
                            look terrific. Easily add photos, text, embed maps
                            and media from other networks. Then share your story
                            with everyone."
                    button={
                        <Button
                            title="VIEW THE STORIES"
                            color="black"
                            space="detail"
                        />
                    }
                />
                <Detail
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/home/desktop/designed-for-everyone.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <source
                                srcSet="/assets/home/tablet/designed-for-everyone.jpg"
                                media={`(min-width:${tablet}px)`}
                            />
                            <img
                                src="/assets/home/mobile/designed-for-everyone.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="
                DESIGNED FOR EVERYONE"
                    paragraph="
                Photosnap can help you create stories that resonate with your audience.  Our 
                tool is designed for photographers of all levels, brands, businesses you name it. "
                    button={
                        <Button
                            title="VIEW THE STORIES"
                            color="black"
                            space="detail"
                        />
                    }
                    order="order"
                />
            </section>

            <section className={styles.section_pictures} aria-label="pictures">
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/mountains.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/mountains.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="The Mountains"
                    author="by John Appleseed"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/cityscapes.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/cityscapes.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Sunset Cityscapes"
                    author=" by Benjamin Cruz"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/18-days-voyage.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/18-days-voyage.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="18 Days Voyage"
                    author="by Alexei Borodin"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/architecturals.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/architecturals.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Architecturals"
                    author="by Samantha Brooke"
                />
            </section>
            <section className={styles.section_tools} aria-label="tools">
                <div className={styles.tools_container}>
                    <Tool
                        icon={<Responsive />}
                        header="100% Responsive"
                        paragraph="No matter which the device you’re on, our site is fully
                        responsive and stories look beautiful on any screen."
                    />
                    <Tool
                        icon={<Unlimit />}
                        header=" No Photo Upload Limit"
                        paragraph="Our tool has no limits on uploads or bandwidth. Freely upload in bulk and 
                    share all of your stories in one go."
                    />
                    <Tool
                        icon={<Embed />}
                        header="Available to Embed"
                        paragraph=" Embed Tweets, Facebook posts, Instagram media, Vimeo or YouTube videos, 
                Google Maps, and more."
                    />
                </div>
            </section>
            <Footer />
        </div>
    );
}
