import Head from "next/head";
import styles from "../styles/Home.module.scss";

import { Header, Button, Detail, Picture, Tool, Footer } from "components";

import { detail } from "../data/detail";
import { pictures } from "../data/pictureIndex";
import { tool } from "../data/toolsIndex";

export default function Home() {
    const desktop = 1180;
    const tablet = 720;

    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Photosnap Website Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />

            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="/assets/home/desktop/create-and-share.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="/assets/home/tablet/create-and-share.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img
                        src="/assets/home/mobile/create-and-share.jpg"
                        alt=""
                    />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info_wrap}>
                        <h1> CREATE AND SHARE YOUR PHOTO STORIES</h1>
                        <p>
                            Photosnap is a platform for photographers and visual
                            storytellers. We make it easy to share photos, tell
                            stories and connect with others.
                        </p>
                        <Button
                            title="GET AN INVITE"
                            color="white"
                            space="main"
                            arrow="white_arrow"
                        />
                    </div>
                </div>
            </main>
            <section className={styles.section_details} aria-label="details">
                {detail.map((item, index) => (
                    <Detail
                        key={index}
                        desktop={item.picture.desktop}
                        tablet={item.picture.tablet}
                        mobile={item.picture.mobile}
                        header={item.header}
                        paragraph={item.paragraph}
                        order={item.order}
                    />
                ))}
            </section>

            <section className={styles.section_pictures} aria-label="pictures">
                {pictures.map((picture, index) => (
                    <Picture
                        key={index}
                        desktop={picture.picture.desktop}
                        mobile={picture.picture.mobile}
                        header={picture.header}
                        author={picture.author}
                    />
                ))}
            </section>
            <section className={styles.section_tools} aria-label="tools">
                <div className={styles.tools_container}>
                    {tool.map((instrument, index) => (
                        <Tool
                            key={index}
                            icon={instrument.icon}
                            header={instrument.header}
                            paragraph={instrument.paragraph}
                        />
                    ))}
                </div>
            </section>
            <Footer />
        </div>
    );
}
