import Head from "next/head";
import styles from "../styles/Pricing.module.scss";
import Header from "../components/Header";
import Beta from "../components/Beta";
import Footer from "../components/Footer";

import Price from "../components/Price";
import Info from "../components/Info";
import Check from "../svg/check.svg";
import { useState } from "react";
export default function Pricing() {
    const [check, setCheck] = useState(false);
    const desktop = 1180;
    const tablet = 720;
    return (
        <div className={styles.main_container}>
            <Head>
                <title>
                    Frontend Mentor | Photosnap Website Challenge |Pricing
                </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>
            <Header />
            <main className={styles.main}>
                <picture className={styles.main_img}>
                    <source
                        srcSet="/assets/pricing/desktop/hero.jpg"
                        media={`(min-width:${desktop}px)`}
                    />
                    <source
                        srcSet="/assets/pricing/tablet/hero.jpg"
                        media={`(min-width:${tablet}px)`}
                    />
                    <img src="/assets/pricing/mobile/hero.jpg" alt="" />
                </picture>
                <div className={styles.main_info}>
                    <div className={styles.info_wrap}>
                        <h1> PRICING</h1>
                        <p>
                            Create a your stories, Photosnap is a platform for
                            photographers and visual storytellers. It’s the
                            simple way to create and share your photos.
                        </p>
                    </div>
                </div>
            </main>
            <section className={styles.section_pricing} aria-label="price">
                <div className={styles.switch_container}>
                    <p
                        className={`${styles.dark} ${
                            check ? styles.light : null
                        }`}
                    >
                        Monthly
                    </p>

                    <input
                        id="input"
                        type="checkbox"
                        className={styles.input}
                        onClick={() => setCheck(!check)}
                    />
                    <label htmlFor="input" className={styles.label}></label>
                    <p className={check ? styles.dark : styles.light}>Yearly</p>
                </div>

                <div className={styles.pricing_container}>
                    <Price
                        header="Basic"
                        paragraph="
                            Includes basic usage of our platform. Recommended
                            for new and aspiring photographers.
                        "
                        price={check ? " $190.00 " : "$19.00 "}
                        period={check ? " per year" : " per month"}
                    />
                    <Price
                        header="Pro"
                        paragraph="
                        More advanced features available. Recommended for photography veterans and professionals.
                        "
                        price={check ? " $390.00 " : "$39.00 "}
                        period={check ? " per year" : " per month"}
                        dark="dark_box"
                        white="white"
                        btn_white="btn_white"
                        light="dark_theme"
                    />
                    <Price
                        header="Business"
                        paragraph="
                    Additional features available such as more detailed metrics. Recommended for business owners.
                    "
                        price={check ? " $990.00 " : "$99.00 "}
                        period={check ? " per year" : " per month"}
                    />
                </div>
            </section>

            <section className={styles.section_table} aria-label="price info ">
                <h2> COMPARE</h2>
                <div className={styles.table_container}>
                    <div className={styles.table_header}>
                        <h4>THE FEATURES</h4>
                        <div className={styles.header_desktop}>
                            <p>BASIC</p>
                            <p>PRO</p>
                            <p>BUSINESS</p>
                        </div>
                    </div>
                    <hr className={`${styles.line} ${styles.darker_line}`} />

                    <Info
                        info="Unlimited Story Posting"
                        basic={<Check />}
                        pro={<Check />}
                        business={<Check />}
                    />
                    <hr className={styles.line} />
                    <Info
                        info="Unlimited Photo Upload"
                        basic={<Check />}
                        pro={<Check />}
                        business={<Check />}
                    />
                    <hr className={styles.line} />
                    <Info
                        info="Embedding Custom Content"
                        pro={<Check />}
                        business={<Check />}
                    />
                    <hr className={styles.line} />
                    <Info
                        info=" Customize Metadata"
                        pro={<Check />}
                        business={<Check />}
                    />
                    <hr className={styles.line} />
                    <Info info=" Advanced Metrics" business={<Check />} />
                    <hr className={styles.line} />
                    <Info info="Photo Downloads" business={<Check />} />
                    <hr className={styles.line} />
                    <Info info="Search Engine Indexing" business={<Check />} />
                    <hr className={styles.line} />
                    <Info info=" Custom Analytics" business={<Check />} />
                    <hr className={styles.line} />
                </div>
            </section>
            <Beta />
            <Footer />
        </div>
    );
}
