import Head from "next/head";
import styles from "../styles/Stories.module.scss";

import Header from "../components/Header";
import Footer from "../components/Footer";
import Button from "../components/Button";
import Picture from "../components/Picture";

export default function Home() {
    const desktop = 1180;

    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Photosnap Website Challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>
            <Header />

            <main className={styles.main}>
                <div className={styles.main_img}>
                    <img
                        src="/assets/stories/mobile/moon-of-appalacia.jpg"
                        alt=""
                    />
                </div>

                <div className={styles.main_info}>
                    <p className={styles.size}>
                        LAST MONTH &apos; S FEATURED STORY
                    </p>
                    <h1> HAZY FULL MOON OF APPALACHIA</h1>
                    <p className={styles.size}>
                        <span>March 2nd 2020 </span> by John Appleseed
                    </p>
                    <p className={styles.paragraph}>
                        The dissected plateau area, while not actually made up
                        of geological mountains, is popularly called
                        &quot;mountains,&quot; especially in eastern Kentucky
                        and West Virginia, and while the ridges are not high,
                        the terrain is extremely rugged.
                    </p>

                    <Button
                        title="READ THE STORY"
                        color="white"
                        space="main"
                        arrow="white_arrow"
                    />
                </div>
            </main>

            <section
                className={styles.section_pictures}
                aria-label="stories pictures"
            >
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/mountains.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/mountains.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="The Mountains"
                    author="by John Appleseed"
                    date=" April 16th 2020"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/cityscapes.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/cityscapes.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Sunset Cityscapes"
                    author=" by Benjamin Cruz"
                    date=" April 14th 2020"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/18-days-voyage.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/18-days-voyage.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="18 Days Voyage"
                    author="by Alexei Borodin"
                    date=" April 11th 2020"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/architecturals.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/architecturals.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Architecturals"
                    author="by Samantha Brooke"
                    date=" April 9th 2020"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/world-tour.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/world-tour.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="World tour 2019"
                    author="by Timothy Wagner"
                    date=" April 7th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/unforeseen-corners.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/unforeseen-corners.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Unforeseen Corners"
                    author="by William Malcolm"
                    date=" April 3th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/king-on-africa.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/king-on-africa.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="King on Africa: Part II"
                    author="by Tim Hillenburg"
                    date=" March 29th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/trip-to-nowhere.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/trip-to-nowhere.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="The Trip to Nowhere"
                    author="by Felicia Rourke"
                    date=" March 21th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/rage-of-the-sea.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/rage-of-the-sea.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header=" Rage of The Sea"
                    author="by  Mohammed Abdul"
                    date=" March 19th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/running-free.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/running-free.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="   Running Free"
                    author="by  Michelle"
                    date=" March 16th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/behind-the-waves.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/behind-the-waves.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="     Behind the Waves"
                    author="by  Lamarr Wilson"
                    date=" March 11th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/calm-waters.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/calm-waters.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Calm Waters"
                    author="by  Samantha Brooke"
                    date=" March 9th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/milky-way.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/milky-way.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="The Milky Way"
                    author="by  Benjamin Cruz"
                    date=" March 5th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/dark-forest.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/dark-forest.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header="Night at The Dark Forest"
                    author="by  Mohammed Abdul"
                    date=" March 4th 2020"
                />

                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/somwarpet.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/somwarpet.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header=" Somwarpet’s Beauty"
                    author="by  Michelle"
                    date=" March 1th 2020"
                />
                <Picture
                    picture={
                        <picture>
                            <source
                                srcSet="/assets/stories/desktop/land-of-dreams.jpg"
                                media={`(min-width:${desktop}px)`}
                            />
                            <img
                                src="/assets/stories/mobile/land-of-dreams.jpg"
                                alt=""
                            />
                        </picture>
                    }
                    header=" Land of Dreams"
                    author="by  William Malcolm"
                    date="  February 25th 2020"
                />
            </section>
            <Footer />
        </div>
    );
}
